services:
  db-dev:
    ports:
      - 5432:5432
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dev
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    external: true
